# Generated by Django 3.0.5 on 2020-10-05 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20201004_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accountno',
            field=models.CharField(default='00000', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='managerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.CharField(choices=[('1', 'Manager'), ('2', 'Engineer'), ('3', 'Accountant')], default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
